name: Generate Snake Animation

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2352ff7d&color_dots=%23e8fff0,%23a5ffbe,%2352ff7d,%232f8f4d,%23153d24
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2352ff7d&color_dots=%23010503,%23153d24,%232f8f4d,%2340c463,%2352ff7d

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
